name: docker-image-alpine-316-openjdk11

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
      - main
    paths:
      - alpine3.16-openjdk11
      - .github/workflows/docker-image-alpine-316-openjdk11.yml
  workflow_dispatch:
jobs:
  pipeline:
    uses: codepraxis-io/github-actions/.github/workflows/docker-build-scan-push-workflow.yml@main
    with:
      docker_context_dir: alpine3.16-openjdk11
      docker_image_name: alpine3.16
      docker_image_tag: openjdk11
    secrets:
      destination_registry_username: ${{ secrets.GH_PACKAGES_USERNAME }} 
      destination_registry_password: ${{ secrets.GH_PAT }}
      cosign_private_key: ${{ secrets.COSIGN_PRIVATE_KEY }} 
      cosign_private_key_password: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
      cosign_public_key: ${{ secrets.COSIGN_PUBLIC_KEY }}
